"""Add approval and contact fields to pandits

Revision ID: 17577e9c376f
Revises: b2115da0791b
Create Date: 2025-12-05 08:13:16.021335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17577e9c376f'
down_revision = 'b2115da0791b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookings_pandit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pandits', ['pandit_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('pandits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('specialties', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pandits', schema=None) as batch_op:
        batch_op.drop_column('is_approved')
        batch_op.drop_column('specialties')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookings_pandit_id_fkey'), 'pandits', ['pandit_id'], ['id'])

    # ### end Alembic commands ###
