"""Add admin and booking tables

Revision ID: b2115da0791b
Revises: 837952855f46
Create Date: 2025-12-05 08:11:07.590974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2115da0791b'
down_revision = '837952855f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookings_pandit_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pandits', ['pandit_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookings_pandit_id_fkey'), 'pandits', ['pandit_id'], ['id'])

    # ### end Alembic commands ###
