"""Add time to booking

Revision ID: d3ab180a738f
Revises: afec71104628
Create Date: 2025-12-30 17:23:00.442761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ab180a738f'
down_revision = 'afec71104628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))
        batch_op.drop_constraint(batch_op.f('bookings_pandit_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('bookings_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pandits', ['pandit_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_items_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('order_items_order_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('order_items_bundle_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bundles', ['bundle_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'puja_materials', ['product_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_items_bundle_id_fkey'), 'bundles', ['bundle_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('order_items_order_id_fkey'), 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('order_items_product_id_fkey'), 'puja_materials', ['product_id'], ['id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookings_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('bookings_pandit_id_fkey'), 'pandits', ['pandit_id'], ['id'])
        batch_op.drop_column('time')

    # ### end Alembic commands ###
